name: dynamic_image_grid
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/dynamic_image_grid/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
  faker:
  flutter_workbench:
    git:
      url: https://github.com/tmcmaster/flutter_workbench.git